name: 'Install NodeJS, Get & Cache Dependencies'
description: 'Install NodeJS, get the dependencies (via npm) and cache them.'
inputs:
  node-version:
    description: 'The version of node to install.'
    required: true
runs:
    using: "composite"
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: inputs.node-version
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        shell: bash
