name: CEFIM 2023 - CI
on:
    workflow_dispatch:
    push:
        branches:
            - main
jobs:
    lint-backend:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 20.x
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                path: node_modules
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-node-
            - name: Install dependencies
              run: npm ci
            - name: Lint backend
              run: npm run lint:backend
    lint-frontend:
      runs-on: ubuntu-latest
      steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 20.x
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                path: node_modules
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-node-
            - name: Install dependencies
              run: npm ci
            - name: Lint frontend
              run: npm run lint:frontend
    test-backend:
        needs: [lint-backend, lint-frontend]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 20.x
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                path: node_modules
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-node-
            - name: Install dependencies
              run: npm ci
            - name: Test code
              run: npm run test -w backend
    test-frontend:
        needs: [lint-backend, lint-frontend]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 20.x
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                path: node_modules
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-node-
            - name: Install dependencies
              run: npm ci
            - name: Test code
              run: npm run test -w frontend
    build-backend:
        needs: [test-backend, test-frontend]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 20.x
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                path: node_modules
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-node-
            - name: Install dependencies
              run: npm ci
            - name: Build backend
              run: npm run build -w backend
            - name: Tar files
              run: tar -cvf dist-backend.tar backend/dist
            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                name: dist-backend
                path: dist-backend.tar
    build-frontend:
        needs: [test-backend, test-frontend]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 20.x
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                path: node_modules
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-node-
            - name: Install dependencies
              run: npm ci
            - name: Build frontend
              run: npm run build -w frontend
            - name: Tar files
              run: tar -cvf dist-frontend.tar frontend/dist
            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                name: dist-frontend
                path: dist-frontend.tar
    release:
        needs: [build-backend, build-frontend]
        runs-on: ubuntu-latest
        steps:
            - name: Get backend build artifacts
              uses: actions/download-artifact@v3
              with:
                name: dist-backend
            - name: Get frontend build artifacts
              uses: actions/download-artifact@v3
              with:
                name: dist-frontend
            - name: Output contents
              run: |
                ls -al
                echo ${{github.ref}}
            - name: release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                files: |
                    dist-backend.tar
                    dist-frontend.tar