name: CEFIM 2023 - CI
on:
    workflow_dispatch:
    push:
        branches:
            - main
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Install dependencies
              run: npm ci
            - name: Lint backend
              run: npm run lint:backend
            - name: Lint frontend
              run: npm run lint:frontend